version: '3.8'

services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=malicook-api
    ports:
      - '5436:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data