version: '3.8'

services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=malicook-api
    ports:
      - '5436:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data

  maildev:
    hostname: maildev
    image: maildev/maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    restart: always
    ports:
      - "1080:80"
      - "25:25"