version: '3.9'

services:
  caddy:
    image: caddy:latest
    container_name: malicook-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
    restart: always

  api:
    container_name: malicook-api
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "5003:5003"
    env_file:
      - .env
    volumes:
      - '.:/app'

volumes:
  caddy_data:
